name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create env file
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          # Create a temporary directory for deployment
          mkdir _site
          cp -r * _site/ 2>/dev/null || :
          
          # Create env.js in the deployment directory
          cat > _site/env.js << EOL
          window.env = {
            OPENAI_API_KEY: '${OPENAI_KEY}',
            SUPABASE_URL: '${SUPABASE_URL}',
            SUPABASE_ANON_KEY: '${SUPABASE_KEY}',
            ENVIRONMENT: 'production'
          };
          EOL
          
          # Verify env.js was created
          echo "Checking env.js..."
          if [ -f _site/env.js ]; then
            echo "env.js created successfully"
            echo "File size: $(wc -c < _site/env.js) bytes"
          else
            echo "Error: env.js not created!"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          publish_dir: ./_site
          force_orphan: true
