name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create env file
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          # Create a temporary directory for deployment
          mkdir _site
          cp -r * _site/ 2>/dev/null || :
          
          # Encode secrets
          OPENAI_ENCODED=$(echo -n "${OPENAI_KEY}" | base64)
          SUPABASE_URL_ENCODED=$(echo -n "${SUPABASE_URL}" | base64)
          SUPABASE_KEY_ENCODED=$(echo -n "${SUPABASE_KEY}" | base64)
          
          # Create env.js with encoded values
          cat > _site/env.js << EOL
          window.env = {
            OPENAI_API_KEY: atob('${OPENAI_ENCODED}'),
            SUPABASE_URL: atob('${SUPABASE_URL_ENCODED}'),
            SUPABASE_ANON_KEY: atob('${SUPABASE_KEY_ENCODED}'),
            ENVIRONMENT: 'production'
          };
          EOL
          
          # Verify env.js was created
          echo "Checking env.js..."
          if [ -f _site/env.js ]; then
            echo "env.js created successfully"
            echo "File size: $(wc -c < _site/env.js) bytes"
          else
            echo "Error: env.js not created!"
            exit 1
          fi

      - name: Setup Git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Clean any existing git remotes
          git remote rm origin || true
          
          # Add the repository as a remote with token authentication
          git remote add origin "https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/${{ github.repository }}.git"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          publish_dir: ./_site
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy to GitHub Pages'
