name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    
    env:
      SUPABASE_URL: ${{ secrets.SECRET_K.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SECRET_K.SUPABASE_ANON_KEY }}
      OPENAI_API_KEY: ${{ secrets.SECRET_K.OPENAI_API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug Secrets Presence
        run: |
          echo "Checking secrets from SECRET_K..."
          echo "SUPABASE_URL exists: ${{ secrets.SECRET_K.SUPABASE_URL != '' }}"
          echo "SUPABASE_ANON_KEY exists: ${{ secrets.SECRET_K.SUPABASE_ANON_KEY != '' }}"
          echo "OPENAI_API_KEY exists: ${{ secrets.SECRET_K.OPENAI_API_KEY != '' }}"
          
          # Debug lengths (safely)
          echo "SUPABASE_URL length: ${#SUPABASE_URL}"
          echo "SUPABASE_ANON_KEY length: ${#SUPABASE_ANON_KEY}"
          echo "OPENAI_API_KEY length: ${#OPENAI_API_KEY}"

      - name: Create and verify env file
        run: |
          # Create env.js with proper formatting
          cat > env.js << 'EOL'
          window.env = {
            OPENAI_API_KEY: "${{ secrets.SECRET_K.OPENAI_API_KEY }}",
            SUPABASE_URL: "${{ secrets.SECRET_K.SUPABASE_URL }}",
            SUPABASE_ANON_KEY: "${{ secrets.SECRET_K.SUPABASE_ANON_KEY }}",
            ENVIRONMENT: "production"
          };
          console.log('Environment loaded:', {
            hasSupabaseUrl: !!window.env.SUPABASE_URL,
            hasSupabaseKey: !!window.env.SUPABASE_ANON_KEY,
            hasOpenAIKey: !!window.env.OPENAI_API_KEY
          });
          EOL

          # Verify env.js
          echo "Verifying env.js..."
          if [ ! -f env.js ]; then
            echo "Error: env.js not created"
            exit 1
          fi

          # Check content (safely)
          echo "Content check:"
          grep -v 'KEY\|URL' env.js || true
          echo "File size: $(wc -c < env.js) bytes"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
