name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Secrets
        run: |
          # Check if secrets exist
          if [ -z "${{ secrets.SUPABASE_URL }}" ]; then
            echo "Error: SUPABASE_URL is not set"
            exit 1
          fi
          if [ -z "${{ secrets.SUPABASE_ANON_KEY }}" ]; then
            echo "Error: SUPABASE_ANON_KEY is not set"
            exit 1
          fi
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "Error: OPENAI_API_KEY is not set"
            exit 1
          fi

          # Validate formats
          if [[ ! "${{ secrets.SUPABASE_URL }}" =~ ^https:// ]]; then
            echo "Error: SUPABASE_URL must start with https://"
            exit 1
          fi
          if [[ ! "${{ secrets.SUPABASE_ANON_KEY }}" =~ ^eyJ ]]; then
            echo "Error: SUPABASE_ANON_KEY must start with eyJ"
            exit 1
          fi
          if [[ ! "${{ secrets.OPENAI_API_KEY }}" =~ ^sk- ]]; then
            echo "Error: OPENAI_API_KEY must start with sk-"
            exit 1
          fi

          echo "✓ All secrets validated successfully"

      - name: Create env.js
        run: |
          cat > env.js << EOF
          window.env = {
            OPENAI_API_KEY: '${{ secrets.OPENAI_API_KEY }}',
            SUPABASE_URL: '${{ secrets.SUPABASE_URL }}',
            SUPABASE_ANON_KEY: '${{ secrets.SUPABASE_ANON_KEY }}',
            ENVIRONMENT: 'production'
          };
          EOF

          # Verify file
          if [ ! -f env.js ] || [ ! -s env.js ]; then
            echo "Error: env.js not created or empty"
            exit 1
          fi

          echo "✓ env.js created successfully"
          echo "File size: $(wc -c < env.js) bytes"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true 