name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Node.js (adjust version as needed)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Prepare Build Directory
      - name: Prepare Build Directory
        run: |
          # Create build directory structure
          mkdir -p build/config
          mkdir -p build/assets

          # Copy static files
          cp index.html build/
          cp styles.css build/
          cp script.js build/
          cp config.js build/
          
          # Copy assets if they exist
          if [ -d "assets" ]; then
            cp -r assets/* build/assets/
          fi
          
          echo "Build directory prepared"
          ls -la build/

      # Generate Environment Configuration
      - name: Generate Environment Configuration
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          # Encode secrets
          OPENAI_ENCODED=$(echo -n "${OPENAI_API_KEY}" | base64)
          SUPABASE_URL_ENCODED=$(echo -n "${SUPABASE_URL}" | base64)
          SUPABASE_KEY_ENCODED=$(echo -n "${SUPABASE_ANON_KEY}" | base64)
          
          # Generate env.js
          cat > build/config/env.js << EOF
          console.log('Loading environment configuration...');
          window.env = {
            OPENAI_API_KEY: atob('${OPENAI_ENCODED}'),
            SUPABASE_URL: atob('${SUPABASE_URL_ENCODED}'),
            SUPABASE_ANON_KEY: atob('${SUPABASE_KEY_ENCODED}'),
            ENVIRONMENT: "production"
          };
          console.log('Environment configuration loaded');
          EOF
          
          echo "Environment configuration generated"
          ls -la build/config/

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy to GitHub Pages'
